
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ProjectType>ProgramLibrary</ProjectType>
		<TargetFramework>net8</TargetFramework>
		<RootNamespace>PepperDash.Essentials.Plugins</RootNamespace>
		<AssemblyName>PepperDash.Essentials.Plugins.Generic.Cec.Display</AssemblyName>
		<Configurations>Debug;Release</Configurations>
		<Deterministic>false</Deterministic>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<AssemblyTitle>EPI.Generic.Cec.Display</AssemblyTitle>
		<Description>PepperDash Essentials plugin for control of generic CEC displays and soundbars.</Description>
		<PackageId>PepperDash.Essentials.Plugins.Generic.Cec.Display</PackageId>
		<PackageProjectUrl>https://github.com/PepperDash/epi-generic-cec-display</PackageProjectUrl>
		<PackageTags>crestron 4series cec display soundbar</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Properties\**" />
		<EmbeddedResource Remove="Properties\**" />
		<None Remove="Properties\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Crestron.SimplSharp.SDK.ProgramLibrary" Version="2.21.128" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="PepperDashEssentials" Version="3.0.0-feat-routing-slot-online-sync.2">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
